### ISSUE TITLE
dijit assets are not accessible

### ISSUE THREAD

**Issue by khomco** [robin850/dojo-rails#1]
I followed README instructions and can successfully load dojo/dojo assets, but when I tried to create a dialog I received a 404 (not found) error when it tried to load "/assets/dijit/Dialog.js".  I see that the assets exist in my gems folder and the 'dijit-rais' is declared in my Gemfile.  Please advise.

**Comment by robin850** [comment]
Hello,

I will look into this tomorrow. Thanks both for using dojo and report this bug. :) 

Have a nice day.

**Comment by robin850** [comment]
Hi mate,

I don't really understand why it doesn't work. I think I should edit the `require` method because in my application.html.erb file for instance, this code just works:

``` ruby
<%= javascript_include_tag "dijit/Dialog" %>
```

But I have the same issue in my javascript assets:

``` coffeescript
require(["dijit/Dialog"], (dialog) ->
  alert "foo bar" # Isn't fired
)
```

**Comment by robin850** [comment]
Hey @khomco, a contributor has just send a pull request in order to fix this problem. I will test an example application with dojox-rails against master and release 0.12.0 this week end if there is no problem. For the moment, you should use the edge version of dojox-rails in you application :

``` ruby
gem 'dojox-rails', :github => "robin850/dojox-rails"
```

Thanks for using this project and report the issue. Have a nice day.

**Comment by khomco** [comment]
Sweet!  Thanks for the update.

Keith Homco :|: Passerby
VP of Product
http://passer.by
@passerby
@khomco

314.609.1500

**Comment by robin850** [comment]
dojox-rails 0.12.0 has been released. I think we can close this for now. Please let me know if you want me to reopen this issue.
